export enum ModalEnum {
  PROFILE = 'PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  OPTIONS = 'OPTIONS',
  CONFIRM_DELETE = 'CONFIRM_DELETE',
  TASK_FORM = 'TASK_FORM',
  USER_FORM = 'USER_FORM',
  GROUP_FORM = 'GROUP_FORM',
  GROUP_SELECTOR = 'GROUP_SELECTOR'
}
