export enum ModalEnum {
  PROFILE = 'PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  TASK_NEW = 'TASK_NEW',
  TASK_OPTIONS = 'TASK_OPTIONS',
  USER_NEW = 'USER_NEW',
  USER_OPTIONS = 'USER_OPTIONS',
  GROUP_SELECTOR = 'GROUP_SELECTOR',
  GROUP_FORM = 'GROUP_FORM',
  GROUP_OPTIONS = 'GROUP_OPTIONS'
}
