export enum ModalEnum {
  PROFILE = 'PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  TASK_NEW = 'TASK_NEW',
  TASK_OPTIONS = 'TASK_OPTIONS',
  USER_NEW = 'USER_NEW',
  USER_OPTIONS = 'USER_OPTIONS'
}
